/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.gui;

public class DlgContato extends javax.swing.JDialog {

    private java.util.List<model.Contato> lstContato = new java.util.ArrayList<>();

    /**
     * Creates new form DlgContato
     */
    public DlgContato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Carrega a lista inicial de contatos
        controller.ContatoController ctl = new controller.ContatoController();
        atualizarLista(ctl.listarContatos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        edtEmail = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAbrirMensagem = new javax.swing.JButton();
        btnFecharTela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Contato");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Email:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAbrirMensagem.setText("Abrir Mensagem");
        btnAbrirMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirMensagemActionPerformed(evt);
            }
        });

        btnFecharTela.setText("Fechar");
        btnFecharTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharTelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addGap(44, 44, 44)
                                .addComponent(btnAbrirMensagem))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(btnFecharTela)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnAbrirMensagem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnFecharTela)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharTelaActionPerformed

        this.dispose();
        DlgBuscaUsuario dlgBuscaCliente = new DlgBuscaUsuario(new javax.swing.JFrame(), true);
        dlgBuscaCliente.setVisible(true); // Torna a tela de busca de cliente visível
    }//GEN-LAST:event_btnFecharTelaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String emailBuscado = edtEmail.getText().trim();
        controller.ContatoController ctl = new controller.ContatoController();
        
        // Filtra por email se houver texto, senão mostra todos
        if (!emailBuscado.isEmpty()) {
            java.util.List<model.Contato> filtrada = ctl.buscarPorEmail(emailBuscado);
            if (filtrada.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Nenhuma mensagem encontrada para este email.", 
                    "Busca", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            atualizarLista(filtrada);
        } else {
            atualizarLista(ctl.listarContatos());
        }
        
        // Limpa o campo de busca
        edtEmail.setText("");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAbrirMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirMensagemActionPerformed
        int indice = jList1.getSelectedIndex();
        if (indice >= 0) {
            model.Contato c = lstContato.get(indice);
            DlgFormularioContato dlgForm = new DlgFormularioContato((java.awt.Frame)getParent(), true, c);
            dlgForm.setVisible(true);
        }
    }//GEN-LAST:event_btnAbrirMensagemActionPerformed

    public void atualizarLista(java.util.List<model.Contato> contatos) {
        lstContato = contatos;
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() { return lstContato.size(); }
            public String getElementAt(int i) {
                model.Contato c = lstContato.get(i);
                java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
                String dataFormatada = c.getDataEnvio().format(formatter);
                return String.format("[%s] %s - %s", 
                    dataFormatada,
                    c.getEmail(), 
                    c.getMensagem());
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirMensagem;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnFecharTela;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
