<<<<<<< HEAD
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.gui;


import controller.ControllerHistoricoReservas;
import controller.PetController;
import controller.ReservaController;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.DefaultListModel;
import model.Pet;
import model.Reserva;


/**
 *
 * @author cayo
 */
public class DlgHistoricoReservas extends javax.swing.JDialog {

    ControllerHistoricoReservas histoController;
    String cpfHisto;
    private PetController petController;
    ReservaController reservaController = new ReservaController();
    
   
    

    public DlgHistoricoReservas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        

        // Inicialização do controlador e variáveis
        histoController = new ControllerHistoricoReservas();
        
        initComponents();
        petController = new PetController(true);
        DefaultListModel<String> listModel = new DefaultListModel<>();
        


    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtnBuscar = new javax.swing.JButton();
        jbtnVisualizar = new javax.swing.JButton();
        panFormulario = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfNomePet = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfCPF = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setText("Historico de Reservas");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Buscar Reserva");

        jbtnBuscar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jbtnBuscar.setText("Buscar");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        jbtnVisualizar.setText("Visualizar detalhes");
        jbtnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVisualizarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("Nome do Pet");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("CPF");

        javax.swing.GroupLayout panFormularioLayout = new javax.swing.GroupLayout(panFormulario);
        panFormulario.setLayout(panFormularioLayout);
        panFormularioLayout.setHorizontalGroup(
            panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfNomePet, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(jtfCPF))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        panFormularioLayout.setVerticalGroup(
            panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfNomePet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(panFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnBuscar)
                            .addComponent(jbtnVisualizar))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jbtnVisualizar)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        try {
        // Pega os valores informados pelo usuário
        String nomePet = jtfNomePet.getText();
        String cpfResponsavel = jtfCPF.getText();

        // Chama o método do controlador para buscar as reservas
        
       List<Reserva> reservas = reservaController.buscarReservasPorNomeOuCpf(nomePet, cpfResponsavel);

        if (reservas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhuma reserva encontrada.", "Resultado", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Exibe as reservas encontradas
            // Aqui você pode, por exemplo, mostrar os resultados em uma lista ou tabela
            for (Reserva reserva : reservas) {
                // Exibir informações da reserva
                System.out.println("Reserva encontrada: " + reserva.toString());
                // Atualize a interface com os dados das reservas, por exemplo:
                // Exibir as informações no JTable ou em uma lista
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao buscar reservas: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
                              
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void lstBuscaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {                                             
        String nomeSelecionado = jList.getSelectedValue();
        if (nomeSelecionado != null) {
             Pet pet = petController.listarTodosPets().stream()
                .filter(h -> h.getNome().equals(nomeSelecionado))
                .findFirst()
                .orElse(null);

        if (pet != null) {
           
            JOptionPane.showMessageDialog(this, "Pet selecionado:\nNome: " + pet.getNome()+
                                               JOptionPane.INFORMATION_MESSAGE);
        }
    }
    }                           
    private void jbtnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVisualizarActionPerformed
       String selecionado = jList.getSelectedValue();
    }//GEN-LAST:event_jbtnVisualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnVisualizar;
    private javax.swing.JTextField jtfCPF;
    private javax.swing.JTextField jtfNomePet;
    private javax.swing.JPanel panFormulario;
    // End of variables declaration//GEN-END:variables
}
=======
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.gui;


import model.HistoricoReserva;
import controller.ControllerHistoricoReservas;
import javax.swing.JOptionPane;
import java.util.List;
import model.RelatorioFuncionario;
import model.Reserva;

/**
 *
 * @author cayo
 */
public class DlgHistoricoReservas extends javax.swing.JDialog {

    private final ControllerHistoricoReservas histoController;

    private String cpfHisto;

    public DlgHistoricoReservas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        // Inicialização do controlador e variáveis
        this.histoController = new ControllerHistoricoReservas();
        this.cpfHisto = "-";

        initComponents();

        // Configurações iniciais
        this.habilitarCampos(false);
        this.limparCampos();

        // Atualiza a tabela com os dados iniciais
        histoController.atualizarTabela(grdHistReser);
    }

    // Método para habilitar ou desabilitar campos
    public void habilitarCampos(boolean flag) {
        edtNomePet.setEnabled(flag);
        edtCPF.setEnabled(flag);
    }

    // Método para limpar os campos de entrada
    public void limparCampos() {
        edtNomePet.setText("");
        edtCPF.setText("");
    }

    // Preenche os campos com os dados de um objeto HistoricoReserva
    public void objetoParaCampos(HistoricoReserva historico) {
        if (historico != null) {
            edtNomePet.setText(historico.getNomePet());
            edtCPF.setText(historico.getCpf());
        }
    }

    // Recupera o objeto selecionado na tabela
    private HistoricoReserva getObjectSelectOnGrid() {
        int rowClicked = grdHistReser.getSelectedRow();
        if (rowClicked >= 0) {
            return (HistoricoReserva) grdHistReser.getModel().getValueAt(rowClicked, -1); // Certifique-se que o modelo suporta isso
        }
        return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edtNomePet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbtnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdHistReser = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        edtCPF = new javax.swing.JTextField();
        jbtnVisualizar = new javax.swing.JButton();
        btnRelatorioEstadiaPet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setText("Historico de Reservas");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Buscar Reserva");

        edtNomePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomePetActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("Nome do Pet");

        jbtnBuscar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jbtnBuscar.setText("Buscar");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        grdHistReser.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        grdHistReser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdHistReserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grdHistReser);

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("CPF");

        jbtnVisualizar.setText("Visualizar detalhes");
        jbtnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVisualizarActionPerformed(evt);
            }
        });

        btnRelatorioEstadiaPet.setText("Gerar Relatorio da Estadia");
        btnRelatorioEstadiaPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioEstadiaPetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edtNomePet, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtnBuscar)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtnVisualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btnRelatorioEstadiaPet)))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtNomePet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(edtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnBuscar)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnVisualizar)
                    .addComponent(btnRelatorioEstadiaPet))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtNomePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomePetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomePetActionPerformed

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        String nomePet = edtNomePet.getText().trim();
        String cpf = edtCPF.getText().trim();

        // Validar os campos de entrada
        if (nomePet.isEmpty() && cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe ao menos um campo para busca.", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Buscar os dados
        List<HistoricoReserva> historicos = histoController.buscarHistoricoReservaCpfAndPetName(cpf, nomePet);
        if (historicos != null && !historicos.isEmpty()) {
            histoController.atualizarTabela(grdHistReser);
        } else {
            JOptionPane.showMessageDialog(this, "Nenhuma reserva encontrada.", "Resultado", JOptionPane.INFORMATION_MESSAGE);
        }                         
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void grdHistReserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdHistReserMouseClicked
         if (evt.getClickCount() == 1) {
            jbtnVisualizarActionPerformed(null);
        }else{
        // Detecta clique na tabela e habilita ações para a linha selecionada
        if (grdHistReser.getSelectedRow() != 1 && grdHistReser.getSelectedRow()!= -1 ) {
        btnRelatorioEstadiaPet.setEnabled(true);
    }

}
    }//GEN-LAST:event_grdHistReserMouseClicked

    private void jbtnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVisualizarActionPerformed
        HistoricoReserva historicoSelecionado = getObjectSelectOnGrid();
        if (historicoSelecionado != null) {
            objetoParaCampos(historicoSelecionado);
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum histórico selecionado.", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbtnVisualizarActionPerformed

    private void btnRelatorioEstadiaPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioEstadiaPetActionPerformed
                                                     
       HistoricoReserva historicoSelecionado = getObjectSelectOnGrid();
    if (historicoSelecionado != null) {
        RelatorioFuncionario relatorioFuncionario = new RelatorioFuncionario();

        relatorioFuncionario.setCpfResponsavel(historicoSelecionado.getCpf());
        relatorioFuncionario.setNomePet(historicoSelecionado.getNomePet());

        DlgRelatorioFuncionario dlgRelatorioFuncionario = new DlgRelatorioFuncionario(new javax.swing.JFrame(), true);
        dlgRelatorioFuncionario.setRelatorioFuncionario(relatorioFuncionario);
        dlgRelatorioFuncionario.carregarRelatorioExistente(relatorioFuncionario);
        dlgRelatorioFuncionario.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Nenhum histórico selecionado.", "Atenção", JOptionPane.WARNING_MESSAGE);
    }

    }//GEN-LAST:event_btnRelatorioEstadiaPetActionPerformed
                                       

private Reserva getReservaSelecionada() {
    // Retorna a reserva selecionada na tabela
    int linhaSelecionada = grdHistReser.getSelectedRow();
    return null;
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRelatorioEstadiaPet;
    private javax.swing.JTextField edtCPF;
    private javax.swing.JTextField edtNomePet;
    private javax.swing.JTable grdHistReser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnVisualizar;
    // End of variables declaration//GEN-END:variables
}
>>>>>>> Main
