/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.gui;
import dao.RelatorioFuncionarioDAO;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import model.RelatorioFuncionario;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import model.Reserva;



/*Essa tela será associada ao Historico de reservas, quando um funcionario buscar e selecionar uma reserva 
que ainda não foi dado checkou ele pode criar observações sobre acontecimentos que ocorreram durante a estadia do pet, 
se algum serviço extra foi necessario e etc. Esta tela serve para garantir que o dono do pet buscou na data correta 
e evita abandono de pets no hotel */

public class DlgRelatorioFuncionario extends javax.swing.JDialog {
    private Connection connection;
    private RelatorioFuncionario relatorioFuncionario;

    public DlgRelatorioFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            // Estabelece a conexão com o banco de dados
            this.connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/seu_banco", "usuario", "senha");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de dados: " + e.getMessage());
        }
    }
    // Suponha que você tenha uma classe de conexão como exemplo
    private void preencherCampos(Reserva reserva) {
    edtCliente.setText(reserva.getCliente().getCpf());
    edtPet.setText(reserva.getPet().getNome());
    checkboxCheckin.setText(new SimpleDateFormat("dd/MM/yyyy").format(reserva.getCheckIn()));
    checkboxCheckOut.setText(reserva.getCheckOut() != null ? 
        new SimpleDateFormat("dd/MM/yyyy").format(reserva.getCheckOut()) : "N/A");
    edtValorPago.setText(String.format("%.2f", reserva.getValorTotal()));
    
    // Marcar checkboxes de acordo com os serviços selecionados
    checkBoxBanho.setSelected(reserva.isServicoBanho());
    checkBoxTosa.setSelected(reserva.isServicoTosa());
    checkBoxPasseio.setSelected(reserva.isServicoPasseio());
    checkBoxAlimentacaoEspecial.setSelected(reserva.isServicoAlimentacaoEspecial());
    
    // Desabilitar edição dos campos
    edtCliente.setEditable(false);
    edtPet.setEditable(false);
    checkboxCheckin.setEnabled(false);
    edtValorPago.setEditable(false);
    checkBoxBanho.setEnabled(false);
    checkBoxTosa.setEnabled(false);
    checkBoxPasseio.setEnabled(false);
    checkBoxAlimentacaoEspecial.setEnabled(false);
}


    public void setRelatorioFuncionario(RelatorioFuncionario relatorioFuncionario) {
        this.relatorioFuncionario = relatorioFuncionario;
        edtCliente.setText(relatorioFuncionario.getCpfResponsavel());
        edtPet.setText(relatorioFuncionario.getNomePet());
        edtDataRealizacaoReserva.setText(relatorioFuncionario.getDataEntrada().toString()); // Corrigido para dataEntrada
        edtValorPago.setText(String.valueOf(relatorioFuncionario.getValorTotal()));

        checkBoxPasseio.setSelected(relatorioFuncionario.isServicoPasseio());
        checkBoxAlimentacaoEspecial.setSelected(relatorioFuncionario.isServicoAlimentacaoEspecial());
        checkBoxBanho.setSelected(relatorioFuncionario.isServicoBanho());
        checkBoxTosa.setSelected(relatorioFuncionario.isServicoTosa());

        txtObservacao.setText(relatorioFuncionario.getObservacoes());
        txtServicoEspecial.setText(relatorioFuncionario.getRotinaEspecial());
        txtComportamentoPet.setText(relatorioFuncionario.getServicosExtras()); // Alterado para servicosExtras
    }
    
    public void setRelatorioFuncionario(RelatorioFuncionario relatorioFuncionario, Reserva reserva) {
    this.relatorioFuncionario = relatorioFuncionario;
    relatorioFuncionario.setCpfResponsavel(reserva.getCliente().getCpf());
    relatorioFuncionario.setNomePet(reserva.getPet().getNome());
}

    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        checkBoxPasseio = new javax.swing.JCheckBox();
        lblCheckIn = new javax.swing.JLabel();
        checkBoxAlimentacaoEspecial = new javax.swing.JCheckBox();
        lblCheckOut = new javax.swing.JLabel();
        checkBoxBanho = new javax.swing.JCheckBox();
        lblValorPago = new javax.swing.JLabel();
        edtDataRealizacaoReserva = new javax.swing.JTextField();
        lbtObservacao = new javax.swing.JLabel();
        edtValorPago = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        edtCliente = new javax.swing.JTextField();
        lblCliente = new javax.swing.JLabel();
        edtPet = new javax.swing.JTextField();
        lblPet = new javax.swing.JLabel();
        checkBoxTosa = new javax.swing.JCheckBox();
        lblServicos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        lblComportamentoPet = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtServicoEspecial = new javax.swing.JTextArea();
        lblServiçoEspecial = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtComportamentoPet = new javax.swing.JTextArea();
        btnSalvar = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();
        checkboxCheckin = new javax.swing.JCheckBox();
        checkboxCheckOut = new javax.swing.JCheckBox();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        checkBoxPasseio.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        checkBoxPasseio.setText("Passeio");

        lblCheckIn.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblCheckIn.setText("Check-in:");

        checkBoxAlimentacaoEspecial.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        checkBoxAlimentacaoEspecial.setText("Alimentação Especial");
        checkBoxAlimentacaoEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAlimentacaoEspecialActionPerformed(evt);
            }
        });

        lblCheckOut.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblCheckOut.setText("Check-out:");

        checkBoxBanho.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        checkBoxBanho.setText("Banho");
        checkBoxBanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxBanhoActionPerformed(evt);
            }
        });

        lblValorPago.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblValorPago.setText("Valor Pago:");

        edtDataRealizacaoReserva.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        lbtObservacao.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lbtObservacao.setText("Observação sobre estadia:");

        edtValorPago.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        edtValorPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtValorPagoActionPerformed(evt);
            }
        });

        lblData.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblData.setText("Data Realização Reserva:");

        lblTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Confirmação de Reservas e Serviços");

        edtCliente.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        edtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtClienteActionPerformed(evt);
            }
        });

        lblCliente.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblCliente.setText("Cliente:");

        edtPet.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        edtPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtPetActionPerformed(evt);
            }
        });

        lblPet.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblPet.setText("Nome Pet:");

        checkBoxTosa.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        checkBoxTosa.setText("Tosa");
        checkBoxTosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxTosaActionPerformed(evt);
            }
        });

        lblServicos.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblServicos.setText("Serviços Realizados:");

        txtObservacao.setColumns(20);
        txtObservacao.setRows(5);
        jScrollPane1.setViewportView(txtObservacao);

        lblComportamentoPet.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblComportamentoPet.setText("Comportamento do Pet:");

        txtServicoEspecial.setColumns(20);
        txtServicoEspecial.setRows(5);
        jScrollPane2.setViewportView(txtServicoEspecial);

        lblServiçoEspecial.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblServiçoEspecial.setText("Serviço especial ou de Emergencia:");

        txtComportamentoPet.setColumns(20);
        txtComportamentoPet.setRows(5);
        jScrollPane3.setViewportView(txtComportamentoPet);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        bntCancelar.setText("Descartar");
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        checkboxCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxCheckinActionPerformed(evt);
            }
        });

        checkboxCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxCheckOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblServiçoEspecial)
                            .addComponent(lblComportamentoPet)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(660, 660, 660)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btnSalvar)
                        .addGap(34, 34, 34)
                        .addComponent(bntCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(checkboxCheckin)
                        .addGap(18, 18, 18)
                        .addComponent(lblCheckOut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtDataRealizacaoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkboxCheckOut))))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbtObservacao)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPet)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(edtPet))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(edtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblValorPago)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(edtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblData)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblCheckIn, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblServicos)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(checkBoxBanho)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(checkBoxTosa)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(checkBoxPasseio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(checkBoxAlimentacaoEspecial)))))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(checkboxCheckin, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(checkboxCheckOut))
                    .addComponent(lblCheckOut, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(edtDataRealizacaoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblServiçoEspecial)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblComportamentoPet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(bntCancelar))
                .addGap(28, 28, 28))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblTitulo)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCliente)
                        .addComponent(edtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPet)
                        .addComponent(edtPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblServicos)
                        .addComponent(checkBoxBanho)
                        .addComponent(checkBoxTosa)
                        .addComponent(checkBoxPasseio)
                        .addComponent(checkBoxAlimentacaoEspecial))
                    .addGap(18, 18, 18)
                    .addComponent(lblCheckIn)
                    .addGap(18, 18, 18)
                    .addComponent(lblData)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblValorPago)
                        .addComponent(edtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(lbtObservacao)
                    .addContainerGap(706, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxAlimentacaoEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAlimentacaoEspecialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxAlimentacaoEspecialActionPerformed

    private void checkBoxBanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxBanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxBanhoActionPerformed

    private void edtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtClienteActionPerformed

    private void checkBoxTosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxTosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxTosaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    if (relatorioFuncionario.isFinalizado()) {
        JOptionPane.showMessageDialog(this, "Este relatório já foi finalizado e não pode ser editado.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Cria um novo objeto com os dados atualizados
    RelatorioFuncionario novoRelatorio = new RelatorioFuncionario();
    novoRelatorio.setId(relatorioFuncionario.getId());
    novoRelatorio.setCpfResponsavel(relatorioFuncionario.getCpfResponsavel());
    novoRelatorio.setNomePet(relatorioFuncionario.getNomePet());
    novoRelatorio.setObservacoes(txtObservacao.getText());
    novoRelatorio.setServicoBanho(checkBoxBanho.isSelected());
    novoRelatorio.setServicoTosa(checkBoxTosa.isSelected());
    novoRelatorio.setServicoPasseio(checkBoxPasseio.isSelected());
    novoRelatorio.setServicoAlimentacaoEspecial(checkBoxAlimentacaoEspecial.isSelected());
    novoRelatorio.setRotinaEspecial(txtServicoEspecial.getText());
    novoRelatorio.setServicosExtras(txtComportamentoPet.getText());
    novoRelatorio.setDataEntrada(relatorioFuncionario.getDataEntrada());
    novoRelatorio.setDataSaida(relatorioFuncionario.getDataSaida());
    novoRelatorio.setValorTotal(Double.parseDouble(edtValorPago.getText()));
    novoRelatorio.setStatusServico(checkboxCheckOut.isSelected() ? "Finalizado" : "Em Andamento");

    try {
        RelatorioFuncionarioDAO dao = new RelatorioFuncionarioDAO(connection);
        dao.update(relatorioFuncionario, novoRelatorio); // Passa o original e o novo
        JOptionPane.showMessageDialog(this, "Relatório salvo com sucesso!");
        dispose(); // Fecha a tela
    } catch (RuntimeException e) {
        JOptionPane.showMessageDialog(this, "Erro ao salvar o relatório: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void checkboxCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxCheckOutActionPerformed
                                                
    // Desativa os campos de edição caso o CheckOut esteja marcado
    if (checkboxCheckOut.isSelected()) {
        toggleCamposEdicao(false);
    } else {
        toggleCamposEdicao(true);
    }

    }//GEN-LAST:event_checkboxCheckOutActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
    this.dispose();
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void edtValorPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtValorPagoActionPerformed
    relatorioFuncionario.calcularValorTotal();
    }//GEN-LAST:event_edtValorPagoActionPerformed

    private void edtPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtPetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtPetActionPerformed

    private void checkboxCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxCheckinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxCheckinActionPerformed
 private void toggleCamposEdicao(boolean habilitar) {
    txtObservacao.setEnabled(habilitar);
    checkBoxBanho.setEnabled(habilitar);
    checkBoxTosa.setEnabled(habilitar);
    checkBoxPasseio.setEnabled(habilitar);
    checkBoxAlimentacaoEspecial.setEnabled(habilitar);
    txtServicoEspecial.setEnabled(habilitar);
    txtComportamentoPet.setEnabled(habilitar);
    edtValorPago.setEnabled(habilitar);
    checkboxCheckOut.setEnabled(habilitar);
}

    public void carregarRelatorioExistente(RelatorioFuncionario relatorio) {
    if (relatorio != null) {
        // Mostra as informações do histórico selecionado na tela
        edtCliente.setText(relatorio.getCpfResponsavel());
        edtPet.setText(relatorio.getNomePet());
        // Preenche os campos com os dados do relatório
        txtObservacao.setText(relatorio.getObservacoes());
        checkBoxBanho.setSelected(relatorio.isServicoBanho());
        checkBoxTosa.setSelected(relatorio.isServicoTosa());
        checkBoxPasseio.setSelected(relatorio.isServicoPasseio());
        checkBoxAlimentacaoEspecial.setSelected(relatorio.isServicoAlimentacaoEspecial());
        txtServicoEspecial.setText(relatorio.getRotinaEspecial());
        txtComportamentoPet.setText(relatorio.getServicosExtras());
        edtValorPago.setText(String.valueOf(relatorio.getValorTotal()));

        // Verifica se o relatório está finalizado e desativa os campos se necessário
        boolean finalizado = relatorio.isFinalizado();
        toggleCamposEdicao(!finalizado); // Desativa os campos se finalizado
        checkboxCheckOut.setSelected(finalizado);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox checkBoxAlimentacaoEspecial;
    private javax.swing.JCheckBox checkBoxBanho;
    private javax.swing.JCheckBox checkBoxPasseio;
    private javax.swing.JCheckBox checkBoxTosa;
    private javax.swing.JCheckBox checkboxCheckOut;
    private javax.swing.JCheckBox checkboxCheckin;
    private javax.swing.JTextField edtCliente;
    private javax.swing.JTextField edtDataRealizacaoReserva;
    private javax.swing.JTextField edtPet;
    private javax.swing.JTextField edtValorPago;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCheckIn;
    private javax.swing.JLabel lblCheckOut;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblComportamentoPet;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblPet;
    private javax.swing.JLabel lblServicos;
    private javax.swing.JLabel lblServiçoEspecial;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorPago;
    private javax.swing.JLabel lbtObservacao;
    private javax.swing.JTextArea txtComportamentoPet;
    private javax.swing.JTextArea txtObservacao;
    private javax.swing.JTextArea txtServicoEspecial;
    // End of variables declaration//GEN-END:variables
}
