/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.gui;

/**
 *
 * @author thais
 */
public class DlgRelatorio extends javax.swing.JDialog {

    /**
     * Creates new form DlgRelatorio
     */
    public DlgRelatorio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EdtLblNomeCliente = new javax.swing.JLabel();
        lblPet = new javax.swing.JLabel();
        edtLblNomePet = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        EdtLblDataNascimentoPet = new javax.swing.JLabel();
        lblRaca = new javax.swing.JLabel();
        edtLblRaca = new javax.swing.JLabel();
        lblCaracteristicasFisicas = new javax.swing.JLabel();
        edtLblCaractéristicasFísicas = new javax.swing.JLabel();
        lblDoencasAlergias = new javax.swing.JLabel();
        edtLblDoencasAlergias = new javax.swing.JLabel();
        lblMedicacoes = new javax.swing.JLabel();
        edtLblMedifcacoes = new javax.swing.JLabel();
        lblObservacoes = new javax.swing.JLabel();
        edtLblObservacoes = new javax.swing.JLabel();
        lblEspecie = new javax.swing.JLabel();
        edtLblEspecie = new javax.swing.JLabel();
        lblPorte = new javax.swing.JLabel();
        edtLblPorte = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        edtLblSexo = new javax.swing.JLabel();
        lblServicos = new javax.swing.JLabel();
        edtLblServicos = new javax.swing.JLabel();
        lblCheckIn = new javax.swing.JLabel();
        edtLblCheckIn = new javax.swing.JLabel();
        lblCheckOut = new javax.swing.JLabel();
        lblEdtCheckOut = new javax.swing.JLabel();
        lblValorPago = new javax.swing.JLabel();
        edtLblValorPago = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        edtLblData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Relatório de Reservas e Serviços");

        lblCliente.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblCliente.setText("Cliente:");

        EdtLblNomeCliente.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        EdtLblNomeCliente.setText("-");

        lblPet.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblPet.setText("Nome Pet:");

        edtLblNomePet.setText("-");

        lblDataNascimento.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblDataNascimento.setText("Data de nascimento: ");

        EdtLblDataNascimentoPet.setText("-");

        lblRaca.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblRaca.setText("Raça:");

        edtLblRaca.setText("-");

        lblCaracteristicasFisicas.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblCaracteristicasFisicas.setText("Caractéristicas Físicas:");

        edtLblCaractéristicasFísicas.setText("-");

        lblDoencasAlergias.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblDoencasAlergias.setText("Histórico de Doenças ou Alergias:");

        edtLblDoencasAlergias.setText("-");

        lblMedicacoes.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblMedicacoes.setText("Medicações Necessárias:");

        edtLblMedifcacoes.setText("-");

        lblObservacoes.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblObservacoes.setText("Observações");

        edtLblObservacoes.setText("-");

        lblEspecie.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblEspecie.setText("Espécie:");

        edtLblEspecie.setText("-");

        lblPorte.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblPorte.setText("Porte:");

        edtLblPorte.setText("-");

        lblSexo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblSexo.setText("Sexo:");

        edtLblSexo.setText("-");

        lblServicos.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblServicos.setText("Serviços Realizados:");

        edtLblServicos.setText("-");

        lblCheckIn.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblCheckIn.setText("Check-in:");

        edtLblCheckIn.setText("-");

        lblCheckOut.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblCheckOut.setText("Check-out:");

        lblEdtCheckOut.setText("-");

        lblValorPago.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblValorPago.setText("Valor Pago:");

        edtLblValorPago.setText("-");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("Realizar FeedBack:");

        lblData.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblData.setText("Data:");

        edtLblData.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtLblDoencasAlergias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtLblNomePet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EdtLblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDataNascimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EdtLblDataNascimentoPet, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRaca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtLblRaca, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))))
                    .addComponent(edtLblCaractéristicasFísicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtLblMedifcacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtLblObservacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblValorPago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtLblValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(179, 179, 179)
                                .addComponent(lblData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtLblData, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCheckIn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtLblCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCheckOut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEdtCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblServicos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtLblServicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblObservacoes)
                            .addComponent(lblMedicacoes)
                            .addComponent(lblDoencasAlergias)
                            .addComponent(lblCaracteristicasFisicas)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEspecie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtLblEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPorte)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtLblPorte, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSexo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtLblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCliente)
                            .addComponent(EdtLblNomeCliente)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPet)
                    .addComponent(edtLblNomePet)
                    .addComponent(lblDataNascimento)
                    .addComponent(EdtLblDataNascimentoPet)
                    .addComponent(lblRaca)
                    .addComponent(edtLblRaca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCaracteristicasFisicas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtLblCaractéristicasFísicas, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDoencasAlergias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtLblDoencasAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMedicacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtLblMedifcacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblObservacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtLblObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspecie)
                    .addComponent(edtLblEspecie)
                    .addComponent(lblPorte)
                    .addComponent(edtLblPorte)
                    .addComponent(lblSexo)
                    .addComponent(edtLblSexo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServicos)
                    .addComponent(edtLblServicos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCheckIn)
                    .addComponent(edtLblCheckIn)
                    .addComponent(lblCheckOut)
                    .addComponent(lblEdtCheckOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorPago)
                    .addComponent(edtLblValorPago)
                    .addComponent(lblData)
                    .addComponent(edtLblData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgRelatorio dialog = new DlgRelatorio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EdtLblDataNascimentoPet;
    private javax.swing.JLabel EdtLblNomeCliente;
    private javax.swing.JLabel edtLblCaractéristicasFísicas;
    private javax.swing.JLabel edtLblCheckIn;
    private javax.swing.JLabel edtLblData;
    private javax.swing.JLabel edtLblDoencasAlergias;
    private javax.swing.JLabel edtLblEspecie;
    private javax.swing.JLabel edtLblMedifcacoes;
    private javax.swing.JLabel edtLblNomePet;
    private javax.swing.JLabel edtLblObservacoes;
    private javax.swing.JLabel edtLblPorte;
    private javax.swing.JLabel edtLblRaca;
    private javax.swing.JLabel edtLblServicos;
    private javax.swing.JLabel edtLblSexo;
    private javax.swing.JLabel edtLblValorPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCaracteristicasFisicas;
    private javax.swing.JLabel lblCheckIn;
    private javax.swing.JLabel lblCheckOut;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblDoencasAlergias;
    private javax.swing.JLabel lblEdtCheckOut;
    private javax.swing.JLabel lblEspecie;
    private javax.swing.JLabel lblMedicacoes;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblPet;
    private javax.swing.JLabel lblPorte;
    private javax.swing.JLabel lblRaca;
    private javax.swing.JLabel lblServicos;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorPago;
    // End of variables declaration//GEN-END:variables
}
